FROM php:7.4-cli

# Move our PHP file into the container
COPY ./php/index.php /usr/src/app/index.php
COPY ./php/bannerStyles.css /usr/src/app/bannerStyles.css

# Move our jQuery files inot the container
RUN mkdir /usr/src/app/jquery
RUN mkdir /usr/src/app/jquery/external
RUN mkdir /usr/src/app/jquery/external/jquery
RUN mkdir /usr/src/app/jquery/images

COPY ./jquery/*.* /usr/src/app/jquery/


# Make things easier if you shell in
WORKDIR /usr/src/app

# Our PHP will be running on port 8000
EXPOSE 8000

# Install the PDO MySQL extension so we can database
RUN docker-php-ext-install pdo_mysql

# Set up a web server
CMD ["php", "-S", "0.0.0.0:8000"]