FROM php:7.4-cli

# Move our PHP file into the container
COPY ./php/index.php /usr/src/app/index.php
COPY ./php/_ajaxcommands.php /usr/src/app/_ajaxcommands.php
COPY ./php/indexJquery.php /usr/src/app/indexJquery.php
COPY ./php/bannerStyles.css /usr/src/app/bannerStyles.css
COPY ./php/_ajaxscriptlibrary.js /usr/src/app/_ajaxscriptlibrary.js
COPY ./php/_newpersonform.js /usr/src/app/_newpersonform.js
COPY ./php/loadPeopleTable.php /usr/src/app/loadPeopleTable.php
COPY ./php/_ajaxpostcommands.php /usr/src/app/_ajaxpostcommands.php
COPY ./php/user_login_page.php /usr/src/app/user_login_page.php
COPY ./php/header.php /usr/src/app/header.php
COPY ./php/footer.php /usr/src/app/footer.php
COPY ./php/login_success.php /usr/src/app/login_success.php
COPY ./php/logout.php /usr/src/app/logout.php
# Move our jQuery files into the container
RUN mkdir /usr/src/app/jquery/
RUN mkdir /usr/src/app/jquery/external/
RUN mkdir /usr/src/app/jquery/external/jquery
RUN mkdir /usr/src/app/jquery/images/
COPY ./jquery/*.* /usr/src/app/jquery/

# Create an image directory
RUN mkdir /usr/src/app/images
COPY ./images/*.* /usr/src/app/images/

ENV user=root
ENV pass=example

# Make things easier if you shell in
WORKDIR /usr/src/app

# Our PHP will be running on port 8000
EXPOSE 8000

# Install the PDO MySQL extension so we can database
RUN docker-php-ext-install pdo_mysql

# Set up a web server
CMD ["php", "-S", "0.0.0.0:8000"]